[target.riscv32imfc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Thal_defaults.x",
]
runner = "blash --port COM7 --monitor-baud 2000000 --"

[unstable]
build-std = ["core"]

[build]
target = "riscv32imfc-unknown-none-elf.json"

[alias]
flash = ["--color=always", "blflash", "--release", "--port=COM7"]
